import type { AnalyticsSummary, Batch, RecyclerMatch, ShipmentHistoryItem, TrackingLog } from './types';

export const demoBatches: Batch[] = [
  {
    batchId: 101,
    title: 'Semester answer sheets',
    paperType: 'Answer sheets',
    weight: 85,
    pagesEstimate: 17000,
    notebooksEstimate: 425,
    status: 'InTransit',
    roomCode: '482913',
    pickupLocation: { lat: 18.5204, lng: 73.8567, address: 'Shivajinagar, Pune' },
    proofUrl: 'https://example.com/proofs/shipment-101-created.jpg',
    proofFileName: 'shipment-101-created.jpg',
    verifiedBy: 'Paperloop Ops',
    verifiedRole: 'admin',
    verificationTimestamp: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    batchId: 102,
    title: 'Unused assignment bundles',
    paperType: 'Assignment paper',
    weight: 120,
    pagesEstimate: 24000,
    notebooksEstimate: 600,
    status: 'Created',
    pickupLocation: { lat: 18.5679, lng: 73.9143, address: 'Viman Nagar, Pune' },
    proofUrl: 'https://example.com/proofs/shipment-102-created.jpg',
    proofFileName: 'shipment-102-created.jpg',
    createdAt: new Date().toISOString(),
  },
  {
    batchId: 103,
    title: 'Library discard papers',
    paperType: 'Mixed office paper',
    weight: 64,
    pagesEstimate: 12800,
    notebooksEstimate: 320,
    status: 'Recycled',
    pickupLocation: { lat: 18.5089, lng: 73.926, address: 'Hadapsar, Pune' },
    proofUrl: 'https://example.com/proofs/shipment-103-recycled.jpg',
    proofFileName: 'shipment-103-recycled.jpg',
    verifiedBy: 'Recycler QA',
    verifiedRole: 'recycler',
    verificationTimestamp: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
    createdAt: new Date().toISOString(),
  },
];

export const demoLogs: TrackingLog[] = [
  {
    batchId: 101,
    status: 'Created',
    actorRole: 'institution',
    message: 'Paper batch created by institution',
    proofUrl: 'https://example.com/proofs/shipment-101-created.jpg',
    proofFileName: 'shipment-101-created.jpg',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 26).toISOString(),
  },
  {
    batchId: 101,
    status: 'Accepted',
    actorRole: 'recycler',
    message: 'Pickup accepted by recycling plant',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 20).toISOString(),
  },
  {
    batchId: 101,
    status: 'PickedUp',
    actorRole: 'recycler',
    message: 'Paper collected from institution',
    proofUrl: 'https://example.com/proofs/shipment-101-pickedup.jpg',
    proofFileName: 'shipment-101-pickedup.jpg',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 14).toISOString(),
  },
  {
    batchId: 101,
    status: 'InTransit',
    actorRole: 'recycler',
    message: 'Batch is moving to the recycling plant',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 9).toISOString(),
  },
];

export const demoAnalytics: AnalyticsSummary = {
  statusCounts: [
    { _id: 'Created', count: 5, weight: 390 },
    { _id: 'InTransit', count: 2, weight: 180 },
    { _id: 'Recycled', count: 4, weight: 460 },
    { _id: 'Delivered', count: 8, weight: 720 },
  ],
  impact: {
    paperKg: 1750,
    notebooksCreated: 8750,
    studentsImpacted: 2916,
    treesSavedEstimate: 29.17,
    waterSavedLitresEstimate: 45500,
    co2SavedKgEstimate: 2555,
  },
};

export const demoRecyclerMatches: RecyclerMatch[] = [
  {
    id: 'recycler-greenloop',
    name: 'GreenLoop Recycling Plant',
    contactName: 'Amit Patil',
    rating: 4.8,
    distanceKm: 5.6,
    phone: '+91 98765 43012',
    email: 'ops@greenloop.example',
    capacityKgPerDay: 900,
    address: 'Shivajinagar, Pune',
  },
  {
    id: 'recycler-paperforge',
    name: 'PaperForge Recyclers',
    contactName: 'Riya Shah',
    rating: 4.6,
    distanceKm: 11.4,
    phone: '+91 98222 45110',
    email: 'pickup@paperforge.example',
    capacityKgPerDay: 650,
    address: 'Kothrud, Pune',
  },
  {
    id: 'recycler-ecopress',
    name: 'EcoPress Notebook Works',
    contactName: 'Sameer Khan',
    rating: 4.4,
    distanceKm: 18.8,
    phone: '+91 99870 22145',
    email: 'desk@ecopress.example',
    capacityKgPerDay: 1200,
    address: 'Hadapsar, Pune',
  },
];

export const demoShipmentHistory: ShipmentHistoryItem[] = [
  {
    id: 'history-001',
    roomName: 'Monsoon Paper Recovery',
    shipmentName: 'FY answer sheet shipment',
    recyclerDetails: 'GreenLoop Recycling Plant · Pune · 4.8 rating',
    ngoDetails: 'Notebook Seva Trust · 640 students',
    totalWeight: 182,
    deliveryProof: 'https://example.com/proofs/history-001-delivery.jpg',
    verificationSummary: 'System verified by NGO on 2026-04-18',
    completedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 18).toISOString(),
  },
  {
    id: 'history-002',
    roomName: 'Library Clearout Drive',
    shipmentName: 'Library discard paper shipment',
    recyclerDetails: 'EcoPress Notebook Works · Hadapsar · 4.4 rating',
    ngoDetails: 'Bright Futures NGO · 420 students',
    totalWeight: 96,
    deliveryProof: 'https://example.com/proofs/history-002-delivery.jpg',
    verificationSummary: 'System verified by NGO on 2026-03-25',
    completedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 42).toISOString(),
  },
];
